name: CI Publish

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check_wrapper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: gradle/actions/wrapper-validation@v4

  build:
    needs: check_wrapper
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
      - uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: temurin
      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}-
      - uses: gradle/actions/setup-gradle@v4
      - run: |
          mkdir -p ~/.gradle
          cp .github/runner-files/ci-gradle.properties ~/.gradle/gradle.properties
      - run: ./gradlew :server:downloadWebUI :server:shadowJar --stacktrace
        env:
          ProductBuildType: "Stable"
      - uses: actions/upload-artifact@v4
        with:
          name: suwa-jar
          path: server/build/*.jar
      - uses: actions/upload-artifact@v4
        with:
          name: suwa-icons
          path: server/src/main/resources/icon
      - run: tar -cvzf scripts.tar.gz scripts/
      - uses: actions/upload-artifact@v4
        with:
          name: suwa-scripts
          path: scripts.tar.gz

  jlink:
    needs: check_wrapper
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: linux-x64
          - os: windows-latest
            name: windows-x64
          - os: macos-14
            name: macOS-arm64
          - os: macos-13
            name: macOS-x64
    steps:
      - uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: temurin
      - run: |
          jlink \
            --add-modules ALL-MODULE-PATH \
            --output suwa \
            --strip-debug \
            --no-man-pages \
            --no-header-files \
            --compress=2
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}-jre
          path: suwa

  bundle:
    needs: [build, jlink]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: debian-all
            jre: linux-x64
          - name: appimage
            jre: linux-x64
          - name: linux-assets
            jre: linux-assets
          - name: linux-x64
            jre: linux-x64
          - name: macOS-x64
            jre: macOS-x64
          - name: macOS-arm64
            jre: macOS-arm64
          - name: windows-x64
            jre: windows-x64
    steps:
      - uses: actions/download-artifact@v5
        with:
          path: artifacts
      - run: |
          mkdir upload/
          tar -xvpf artifacts/suwa-scripts/scripts.tar.gz
          scripts/bundler.sh -o upload/ ${{ matrix.name }}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: upload/*

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: bundle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v5
        with:
          path: release
      - run: cd release && sha256sum * > Checksums.sha256
      - uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: release/*
